platform :ios, '7.0'
use_frameworks!

target 'SwiftPractice' do

pod 'MBProgressHUD'

end

target 'SwiftPracticeTests' do

end

target 'SwiftPracticeUITests' do

end

target 'BitWatch' do
platform :watchos, '2.0'
end

