# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Test1' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Test1

  pod 'MBProgressHUD'
  #pod 'SignalR-ObjC', '~> 2.0'
  pod 'SwiftSignalRClient', '0.9.3'
  pod 'AFNetworking'

end
