# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'

target 'SwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'ReachabilitySwift','5.0.0'
  pod 'Alamofire','5.7.1'
  pod 'Toast','4.0.0'
  pod 'MBProgressHUD','1.2.0'
  #pod "ToastViewSwift"
  pod 'PowerplayToastKit'
  pod 'ZLImageEditor'
  pod 'TagListView'
  pod "TTGTagCollectionView"
  pod 'YUCIHighPassSkinSmoothing', '1.4'
  
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
               end
          end
   end
end
